# Generated by Django 5.1.15 on 2026-06-30 12:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=8, unique=True)),
                ('available', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_currency', models.CharField(max_length=8)),
                ('receive_currency', models.CharField(max_length=8)),
                ('networks', models.CharField(default='TON,TRON', max_length=64)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=12)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Overrides the global commission when set.', max_digits=5, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['send_currency', 'receive_currency'],
                'unique_together': {('send_currency', 'receive_currency')},
            },
        ),
    ]
