# Generated by Django 5.1.15 on 2026-06-30 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('quoted', 'Quoted'), ('payin_pending', 'Pay-in pending'), ('payin_settled', 'Pay-in settled (USDT received)'), ('onchain_sent', 'On-chain transfer sent'), ('payout_pending', 'Payout pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=16)),
                ('send_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('send_currency', models.CharField(max_length=8)),
                ('receive_currency', models.CharField(max_length=8)),
                ('recipient_card_last4', models.CharField(max_length=4)),
                ('recipient_reference', models.CharField(blank=True, max_length=128)),
                ('network', models.CharField(max_length=10)),
                ('usdt_transferred', models.DecimalField(decimal_places=6, max_digits=18)),
                ('receive_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('network_fee_usdt', models.DecimalField(decimal_places=6, max_digits=18)),
                ('payin_ref', models.CharField(blank=True, max_length=128)),
                ('chain_tx', models.CharField(blank=True, max_length=128)),
                ('payout_ref', models.CharField(blank=True, max_length=128)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='wallets.paymentcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('currency', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='transfers.transfer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
