# Generated by Django 5.1.15 on 2026-06-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='error',
            field=models.TextField(blank=True),
        ),
    ]
