# Generated by Django 5.1.15 on 2026-06-30 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_webhookevent_attempts_webhookevent_error'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('quoted', 'Quoted'), ('payin_pending', 'Pay-in pending'), ('payin_settled', 'Pay-in settled (USDT received)'), ('approval_pending', 'Awaiting treasury approval'), ('onchain_sent', 'On-chain transfer sent'), ('payout_pending', 'Payout pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=16),
        ),
        migrations.CreateModel(
            name='OnchainApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approvers', models.ManyToManyField(blank=True, related_name='onchain_approvals', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_approval', to='transfers.transfer')),
            ],
        ),
    ]
