# Generated by Django 5.1.15 on 2026-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_alter_transfer_status_onchainapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='recipient_brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_card_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
