# Generated by Django 5.1.15 on 2026-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_transfer_recipient_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='refund_ref',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
