# Generated by Django 5.1.15 on 2026-06-30 14:39

import ubique.common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_transfer_refund_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='recipient_card_token',
            field=ubique.common.encryption.EncryptedCharField(blank=True, max_length=255),
        ),
    ]
