# Generated by Django 5.1.15 on 2026-06-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0008_webhookendpoint_outbounddelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='review_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='risk_decision',
            field=models.CharField(default='allow', max_length=10),
        ),
        migrations.AddField(
            model_name='transfer',
            name='risk_reasons',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfer',
            name='risk_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
