# Generated by Django 5.1.15 on 2026-06-30 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0009_transfer_review_released_transfer_risk_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won (in our favour)'), ('charged_back', 'Charged back (funds lost)')], default='open', max_length=14)),
                ('resolution', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='transfers.transfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
