# Generated by Django 5.1.15 on 2026-06-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telegram_id_user_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_treasury_signer',
            field=models.BooleanField(default=False),
        ),
    ]
