# Generated by Django 5.1.15 on 2026-06-30 14:39

import ubique.common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='provider_token',
            field=ubique.common.encryption.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='card_token',
            field=ubique.common.encryption.EncryptedCharField(max_length=255),
        ),
    ]
